name: 사이트 빌드
on:
  push:
    branches: [ main ]
    paths:
      - 'data/*.json'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: python app.py
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v4
      with:
        path: './outputs'
    - uses: actions/deploy-pages@v4
      id: deployment
